name: Forcefield
description: Forcefield for EmrahOKLM
author: Zeldown
version: 1.0
main: be.zeldown.forcefield.Forcefield
api-version: 1.16

commands:
 forcefield:
   description: forcefield command
   usage: ff
   aliases: [forcef, ffield]